In [ ]:
# !kaggle competitions download -c kkbox-churn-prediction-challenge

Downloading kkbox-churn-prediction-challenge.zip to c:\SKN24\ML_2nd

  0%|          | 0.00/8.34G [00:00<?, ?B/s]
  0%|          | 1.00M/8.34G [00:00<34:43, 4.30MB/s]
  0%|          | 4.00M/8.34G [00:00<11:56, 12.5MB/s]
  0%|          | 7.00M/8.34G [00:00<08:44, 17.1MB/s]
  0%|          | 10.0M/8.34G [00:00<07:30, 19.9MB/s]
  0%|          | 13.0M/8.34G [00:00<07:40, 19.4MB/s]
  0%|          | 17.0M/8.34G [00:00<06:29, 22.9MB/s]
  0%|          | 20.0M/8.34G [00:01<06:23, 23.3MB/s]
  0%|          | 24.0M/8.34G [00:01<05:41, 26.1MB/s]
  0%|          | 27.0M/8.34G [00:01<07:16, 20.4MB/s]
  0%|          | 31.0M/8.34G [00:01<06:18, 23.6MB/s]
  0%|          | 34.0M/8.34G [00:01<05:56, 25.0MB/s]
  0%|          | 37.0M/8.34G [00:01<06:05, 24.4MB/s]
  0%|          | 40.0M/8.34G [00:01<05:44, 25.9MB/s]
  1%|          | 43.0M/8.34G [00:02<05:40, 26.2MB/s]
  1%|          | 46.0M/8.34G [00:02<06:19, 23.4MB/s]
  1%|          | 50.0M/8.34G [00:02<05:42, 26.0MB/s]
  1%|          | 53.0M/8.34G [00:02<05:28, 27.1MB/s]
  1%|          | 57.0M/8.34G [00:02<05:09, 28.8MB/s]
  1%|          | 61.0M/8.34G [00:02<04:56, 30.0MB/s]
  1%|          | 64.0M/8.34G [00:02<05:16, 28.1MB/s]
  1%|          | 68.0M/8.34G [00:02<05:02, 29.3MB/s]
  1%|          | 71.0M/8.34G [00:03<04:59, 29.7MB/s]
  1%|          | 74.0M/8.34G [00:03<05:03, 29.3MB/s]
  1%|          | 77.0M/8.34G [00:03<04:58, 29.7MB/s]
  1%|          | 81.0M/8.34G [00:03<04:47, 30.9MB/s]
  1%|          | 84.0M/8.34G [00:03<05:04, 29.1MB/s]
  1%|          | 88.0M/8.34G [00:03<04:44, 31.1MB/s]
  1%|          | 91.0M/8.34G [00:03<04:47, 30.8MB/s]
  1%|          | 94.0M/8.34G [00:03<04:47, 30.8MB/s]
  1%|          | 97.0M/8.34G [00:03<04:45, 31.0MB/s]
  1%|          | 100M/8.34G [00:04<06:19, 23.3MB/s]
  1%|          | 103M/8.34G [00:04<06:49, 21.6MB/s]
  1%|          | 106M/8.34G [00:04<07:37, 19.3MB/s]
  1%|▏         | 109M/8.34G [00:04<07:34, 19.4MB/s]
  1%|▏         | 111M/8.34G [00:04<08:35, 17.1MB/s]
  1%|▏         | 113M/8.34G [00:05<08:59, 16.4MB/s]
  1%|▏         | 115M/8.34G [00:05<09:16, 15.9MB/s]
  1%|▏         | 118M/8.34G [00:05<08:08, 18.1MB/s]
  1%|▏         | 120M/8.34G [00:05<09:36, 15.3MB/s]
  1%|▏         | 122M/8.34G [00:05<09:35, 15.3MB/s]
  1%|▏         | 125M/8.34G [00:05<08:54, 16.5MB/s]
  1%|▏         | 127M/8.34G [00:05<09:17, 15.8MB/s]
  2%|▏         | 129M/8.34G [00:06<09:26, 15.6MB/s]
  2%|▏         | 132M/8.34G [00:06<09:38, 15.2MB/s]
  2%|▏         | 134M/8.34G [00:06<09:32, 15.4MB/s]
  2%|▏         | 136M/8.34G [00:06<09:05, 16.2MB/s]
  2%|▏         | 138M/8.34G [00:06<08:48, 16.7MB/s]
  2%|▏         | 141M/8.34G [00:06<08:01, 18.3MB/s]
  2%|▏         | 144M/8.34G [00:06<07:42, 19.0MB/s]
  2%|▏         | 146M/8.34G [00:07<07:57, 18.4MB/s]
  2%|▏         | 149M/8.34G [00:07<07:08, 20.5MB/s]
  2%|▏         | 151M/8.34G [00:07<07:25, 19.8MB/s]
  2%|▏         | 155M/8.34G [00:07<06:13, 23.5MB/s]
  2%|▏         | 159M/8.34G [00:07<05:31, 26.5MB/s]
  2%|▏         | 163M/8.34G [00:07<05:07, 28.6MB/s]
  2%|▏         | 167M/8.34G [00:07<04:56, 29.6MB/s]
  2%|▏         | 171M/8.34G [00:08<06:40, 21.9MB/s]
  2%|▏         | 174M/8.34G [00:08<08:22, 17.5MB/s]
  2%|▏         | 178M/8.34G [00:08<07:04, 20.7MB/s]
  2%|▏         | 181M/8.34G [00:08<06:26, 22.7MB/s]
  2%|▏         | 185M/8.34G [00:08<05:48, 25.2MB/s]
  2%|▏         | 189M/8.34G [00:08<05:20, 27.3MB/s]
  2%|▏         | 193M/8.34G [00:08<04:55, 29.6MB/s]
  2%|▏         | 197M/8.34G [00:09<06:48, 21.4MB/s]
  2%|▏         | 201M/8.34G [00:09<06:06, 23.8MB/s]
  2%|▏         | 204M/8.34G [00:09<06:11, 23.5MB/s]
  2%|▏         | 207M/8.34G [00:09<07:02, 20.7MB/s]
  2%|▏         | 210M/8.34G [00:09<06:49, 21.3MB/s]
  2%|▏         | 213M/8.34G [00:10<06:13, 23.4MB/s]
  3%|▎         | 217M/8.34G [00:10<06:52, 21.1MB/s]
  3%|▎         | 221M/8.34G [00:10<06:08, 23.7MB/s]
  3%|▎         | 224M/8.34G [00:10<05:45, 25.2MB/s]
  3%|▎         | 227M/8.34G [00:10<06:30, 22.3MB/s]
  3%|▎         | 230M/8.34G [00:10<06:12, 23.4MB/s]
  3%|▎         | 233M/8.34G [00:10<05:59, 24.2MB/s]
  3%|▎         | 236M/8.34G [00:11<05:44, 25.3MB/s]
  3%|▎         | 239M/8.34G [00:11<05:52, 24.7MB/s]
  3%|▎         | 243M/8.34G [00:11<05:26, 26.6MB/s]
  3%|▎         | 247M/8.34G [00:11<05:10, 28.0MB/s]
  3%|▎         | 251M/8.34G [00:11<04:49, 30.0MB/s]
  3%|▎         | 256M/8.34G [00:11<04:15, 34.0MB/s]
  3%|▎         | 260M/8.34G [00:11<04:24, 32.9MB/s]
  3%|▎         | 264M/8.34G [00:11<04:27, 32.4MB/s]
  3%|▎         | 268M/8.34G [00:12<04:24, 32.7MB/s]
  3%|▎         | 272M/8.34G [00:12<04:28, 32.2MB/s]
  3%|▎         | 276M/8.34G [00:12<04:26, 32.5MB/s]
  3%|▎         | 280M/8.34G [00:12<04:29, 32.2MB/s]
  3%|▎         | 284M/8.34G [00:12<04:32, 31.8MB/s]
  3%|▎         | 288M/8.34G [00:12<04:33, 31.6MB/s]
  3%|▎         | 292M/8.34G [00:12<04:30, 31.9MB/s]
  3%|▎         | 296M/8.34G [00:13<04:36, 31.3MB/s]
  4%|▎         | 300M/8.34G [00:13<04:25, 32.6MB/s]
  4%|▎         | 304M/8.34G [00:13<04:33, 31.6MB/s]
  4%|▎         | 308M/8.34G [00:13<04:26, 32.4MB/s]
  4%|▎         | 312M/8.34G [00:13<04:28, 32.1MB/s]
  4%|▎         | 316M/8.34G [00:13<04:39, 30.9MB/s]
  4%|▎         | 319M/8.34G [00:13<05:07, 28.0MB/s]
  4%|▍         | 323M/8.34G [00:13<04:54, 29.3MB/s]
  4%|▍         | 326M/8.34G [00:14<06:01, 23.8MB/s]
  4%|▍         | 329M/8.34G [00:14<05:46, 24.9MB/s]
  4%|▍         | 332M/8.34G [00:14<06:48, 21.0MB/s]
  4%|▍         | 335M/8.34G [00:14<06:29, 22.1MB/s]
  4%|▍         | 339M/8.34G [00:14<05:41, 25.1MB/s]
  4%|▍         | 343M/8.34G [00:14<05:19, 26.9MB/s]
  4%|▍         | 347M/8.34G [00:14<04:58, 28.7MB/s]
  4%|▍         | 351M/8.34G [00:15<04:46, 29.9MB/s]
  4%|▍         | 354M/8.34G [00:15<05:23, 26.6MB/s]
  4%|▍         | 357M/8.34G [00:15<05:18, 26.9MB/s]
  4%|▍         | 360M/8.34G [00:15<05:18, 26.9MB/s]
  4%|▍         | 364M/8.34G [00:15<05:00, 28.5MB/s]
  4%|▍         | 367M/8.34G [00:15<05:18, 26.9MB/s]
  4%|▍         | 370M/8.34G [00:15<05:32, 25.7MB/s]
  4%|▍         | 373M/8.34G [00:15<05:21, 26.6MB/s]
  4%|▍         | 376M/8.34G [00:16<05:13, 27.3MB/s]
  4%|▍         | 379M/8.34G [00:16<05:13, 27.3MB/s]
  4%|▍         | 382M/8.34G [00:16<05:48, 24.6MB/s]
  5%|▍         | 385M/8.34G [00:16<05:40, 25.1MB/s]
  5%|▍         | 389M/8.34G [00:16<05:10, 27.5MB/s]
  5%|▍         | 392M/8.34G [00:16<05:03, 28.2MB/s]
  5%|▍         | 395M/8.34G [00:16<05:35, 25.4MB/s]
  5%|▍         | 399M/8.34G [00:17<05:09, 27.6MB/s]
  5%|▍         | 403M/8.34G [00:17<04:53, 29.0MB/s]
  5%|▍         | 407M/8.34G [00:17<04:44, 30.0MB/s]
  5%|▍         | 411M/8.34G [00:17<04:35, 30.9MB/s]
  5%|▍         | 414M/8.34G [00:17<04:40, 30.4MB/s]
  5%|▍         | 418M/8.34G [00:17<04:31, 31.4MB/s]
  5%|▍         | 422M/8.34G [00:17<04:34, 31.1MB/s]
  5%|▍         | 426M/8.34G [00:17<04:29, 31.5MB/s]
  5%|▌         | 430M/8.34G [00:18<04:26, 31.9MB/s]
  5%|▌         | 434M/8.34G [00:18<04:34, 30.9MB/s]
  5%|▌         | 437M/8.34G [00:18<04:34, 30.9MB/s]
  5%|▌         | 440M/8.34G [00:18<04:45, 29.8MB/s]
  5%|▌         | 443M/8.34G [00:18<05:03, 27.9MB/s]
  5%|▌         | 446M/8.34G [00:18<05:02, 28.0MB/s]
  5%|▌         | 449M/8.34G [00:18<04:58, 28.4MB/s]
  5%|▌         | 452M/8.34G [00:18<04:51, 29.1MB/s]
  5%|▌         | 455M/8.34G [00:18<04:51, 29.1MB/s]
  5%|▌         | 459M/8.34G [00:19<04:44, 29.7MB/s]
  5%|▌         | 463M/8.34G [00:19<05:34, 25.3MB/s]
  5%|▌         | 467M/8.34G [00:19<05:06, 27.6MB/s]
  6%|▌         | 470M/8.34G [00:19<06:06, 23.1MB/s]
  6%|▌         | 473M/8.34G [00:19<06:15, 22.5MB/s]
  6%|▌         | 477M/8.34G [00:19<05:29, 25.7MB/s]
  6%|▌         | 481M/8.34G [00:19<04:47, 29.4MB/s]
  6%|▌         | 485M/8.34G [00:20<04:50, 29.0MB/s]
  6%|▌         | 488M/8.34G [00:20<05:04, 27.7MB/s]
  6%|▌         | 492M/8.34G [00:20<04:50, 29.0MB/s]
  6%|▌         | 496M/8.34G [00:20<04:35, 30.6MB/s]
  6%|▌         | 500M/8.34G [00:20<04:28, 31.4MB/s]
  6%|▌         | 504M/8.34G [00:20<04:30, 31.2MB/s]
  6%|▌         | 508M/8.34G [00:20<04:31, 31.1MB/s]
  6%|▌         | 511M/8.34G [00:21<04:55, 28.5MB/s]
  6%|▌         | 514M/8.34G [00:21<04:53, 28.7MB/s]
  6%|▌         | 517M/8.34G [00:21<04:59, 28.1MB/s]
  6%|▌         | 520M/8.34G [00:21<05:11, 27.0MB/s]
  6%|▌         | 523M/8.34G [00:21<05:05, 27.5MB/s]
  6%|▌         | 527M/8.34G [00:21<04:43, 29.6MB/s]
  6%|▌         | 531M/8.34G [00:21<04:30, 31.0MB/s]
  6%|▋         | 535M/8.34G [00:21<04:18, 32.4MB/s]
  6%|▋         | 539M/8.34G [00:21<04:13, 33.1MB/s]
  6%|▋         | 543M/8.34G [00:22<04:39, 29.9MB/s]
  6%|▋         | 546M/8.34G [00:22<05:16, 26.5MB/s]
  6%|▋         | 550M/8.34G [00:22<04:54, 28.5MB/s]
  6%|▋         | 554M/8.34G [00:22<04:44, 29.4MB/s]
  7%|▋         | 558M/8.34G [00:22<04:32, 30.7MB/s]
  7%|▋         | 561M/8.34G [00:22<04:31, 30.8MB/s]
  7%|▋         | 564M/8.34G [00:22<04:38, 30.0MB/s]
  7%|▋         | 568M/8.34G [00:23<04:33, 30.6MB/s]
  7%|▋         | 571M/8.34G [00:23<04:31, 30.7MB/s]
  7%|▋         | 575M/8.34G [00:23<04:17, 32.4MB/s]
  7%|▋         | 579M/8.34G [00:23<04:16, 32.5MB/s]
  7%|▋         | 583M/8.34G [00:23<04:37, 30.1MB/s]
  7%|▋         | 587M/8.34G [00:23<04:27, 31.1MB/s]
  7%|▋         | 591M/8.34G [00:23<06:06, 22.7MB/s]
  7%|▋         | 595M/8.34G [00:24<05:33, 25.0MB/s]
  7%|▋         | 599M/8.34G [00:24<05:06, 27.2MB/s]
  7%|▋         | 603M/8.34G [00:24<04:49, 28.7MB/s]
  7%|▋         | 607M/8.34G [00:24<04:33, 30.4MB/s]
  7%|▋         | 611M/8.34G [00:24<04:22, 31.7MB/s]
  7%|▋         | 615M/8.34G [00:24<05:15, 26.3MB/s]
  7%|▋         | 618M/8.34G [00:24<05:23, 25.7MB/s]
  7%|▋         | 622M/8.34G [00:25<04:53, 28.3MB/s]
  7%|▋         | 626M/8.34G [00:25<04:39, 29.7MB/s]
  7%|▋         | 630M/8.34G [00:25<04:25, 31.2MB/s]
  7%|▋         | 634M/8.34G [00:25<04:25, 31.2MB/s]
  7%|▋         | 638M/8.34G [00:25<04:20, 31.8MB/s]
  8%|▊         | 642M/8.34G [00:25<04:18, 32.0MB/s]
  8%|▊         | 646M/8.34G [00:25<04:14, 32.5MB/s]
  8%|▊         | 650M/8.34G [00:25<04:13, 32.6MB/s]
  8%|▊         | 654M/8.34G [00:26<04:16, 32.3MB/s]
  8%|▊         | 658M/8.34G [00:26<04:16, 32.2MB/s]
  8%|▊         | 662M/8.34G [00:26<04:15, 32.3MB/s]
  8%|▊         | 666M/8.34G [00:26<05:09, 26.7MB/s]
  8%|▊         | 669M/8.34G [00:26<05:05, 27.1MB/s]
  8%|▊         | 672M/8.34G [00:26<05:06, 26.9MB/s]
  8%|▊         | 675M/8.34G [00:26<05:08, 26.7MB/s]
  8%|▊         | 678M/8.34G [00:27<05:03, 27.1MB/s]
  8%|▊         | 681M/8.34G [00:27<04:57, 27.7MB/s]
  8%|▊         | 684M/8.34G [00:27<04:47, 28.7MB/s]
  8%|▊         | 688M/8.34G [00:27<04:32, 30.2MB/s]
  8%|▊         | 691M/8.34G [00:27<04:42, 29.1MB/s]
  8%|▊         | 695M/8.34G [00:27<04:26, 30.9MB/s]
  8%|▊         | 699M/8.34G [00:27<04:21, 31.5MB/s]
  8%|▊         | 704M/8.34G [00:27<04:15, 32.1MB/s]
  8%|▊         | 708M/8.34G [00:28<04:16, 32.0MB/s]
  8%|▊         | 712M/8.34G [00:28<05:35, 24.5MB/s]
  8%|▊         | 715M/8.34G [00:28<05:17, 25.9MB/s]
  8%|▊         | 719M/8.34G [00:28<04:52, 28.1MB/s]
  8%|▊         | 723M/8.34G [00:28<04:40, 29.2MB/s]
  9%|▊         | 727M/8.34G [00:28<04:32, 30.1MB/s]
  9%|▊         | 731M/8.34G [00:28<04:26, 30.7MB/s]
  9%|▊         | 735M/8.34G [00:29<04:20, 31.4MB/s]
  9%|▊         | 739M/8.34G [00:29<04:27, 30.5MB/s]
  9%|▊         | 743M/8.34G [00:29<04:24, 30.9MB/s]
  9%|▊         | 747M/8.34G [00:29<04:22, 31.2MB/s]
  9%|▉         | 750M/8.34G [00:29<04:29, 30.3MB/s]
  9%|▉         | 753M/8.34G [00:29<05:33, 24.5MB/s]
  9%|▉         | 756M/8.34G [00:29<05:18, 25.6MB/s]
  9%|▉         | 759M/8.34G [00:30<05:42, 23.8MB/s]
  9%|▉         | 762M/8.34G [00:30<06:25, 21.2MB/s]
  9%|▉         | 765M/8.34G [00:30<06:02, 22.5MB/s]
  9%|▉         | 768M/8.34G [00:30<05:33, 24.4MB/s]
  9%|▉         | 772M/8.34G [00:30<05:06, 26.6MB/s]
  9%|▉         | 775M/8.34G [00:30<04:57, 27.3MB/s]
  9%|▉         | 778M/8.34G [00:30<04:47, 28.3MB/s]
  9%|▉         | 781M/8.34G [00:30<04:44, 28.6MB/s]
  9%|▉         | 785M/8.34G [00:31<04:42, 28.8MB/s]
  9%|▉         | 788M/8.34G [00:31<04:55, 27.5MB/s]
  9%|▉         | 791M/8.34G [00:31<04:55, 27.5MB/s]
  9%|▉         | 794M/8.34G [00:31<04:55, 27.5MB/s]
  9%|▉         | 798M/8.34G [00:31<04:34, 29.6MB/s]
  9%|▉         | 802M/8.34G [00:31<04:22, 30.9MB/s]
  9%|▉         | 806M/8.34G [00:31<04:22, 30.9MB/s]
  9%|▉         | 810M/8.34G [00:31<04:22, 30.9MB/s]
 10%|▉         | 814M/8.34G [00:32<04:22, 30.9MB/s]
 10%|▉         | 817M/8.34G [00:32<04:30, 30.0MB/s]
 10%|▉         | 820M/8.34G [00:32<04:31, 29.9MB/s]
 10%|▉         | 823M/8.34G [00:32<04:38, 29.1MB/s]
 10%|▉         | 826M/8.34G [00:32<04:40, 28.9MB/s]
 10%|▉         | 830M/8.34G [00:32<04:10, 32.2MB/s]
 10%|▉         | 834M/8.34G [00:32<04:11, 32.2MB/s]
 10%|▉         | 838M/8.34G [00:32<04:32, 29.7MB/s]
 10%|▉         | 842M/8.34G [00:32<04:23, 30.6MB/s]
 10%|▉         | 845M/8.34G [00:33<04:39, 28.9MB/s]
 10%|▉         | 848M/8.34G [00:33<04:42, 28.5MB/s]
 10%|▉         | 851M/8.34G [00:33<04:42, 28.5MB/s]
 10%|█         | 854M/8.34G [00:33<04:42, 28.5MB/s]
 10%|█         | 857M/8.34G [00:33<04:44, 28.3MB/s]
 10%|█         | 860M/8.34G [00:33<04:40, 28.7MB/s]
 10%|█         | 863M/8.34G [00:33<04:39, 28.8MB/s]
 10%|█         | 866M/8.34G [00:33<04:41, 28.5MB/s]
 10%|█         | 869M/8.34G [00:34<04:44, 28.3MB/s]
 10%|█         | 872M/8.34G [00:34<04:47, 27.9MB/s]
 10%|█         | 875M/8.34G [00:34<04:48, 27.9MB/s]
 10%|█         | 879M/8.34G [00:34<04:32, 29.4MB/s]
 10%|█         | 882M/8.34G [00:34<04:31, 29.6MB/s]
 10%|█         | 886M/8.34G [00:34<04:17, 31.1MB/s]
 10%|█         | 890M/8.34G [00:34<04:15, 31.4MB/s]
 10%|█         | 893M/8.34G [00:34<04:15, 31.4MB/s]
 10%|█         | 896M/8.34G [00:34<04:26, 30.0MB/s]
 11%|█         | 899M/8.34G [00:35<05:16, 25.3MB/s]
 11%|█         | 902M/8.34G [00:35<06:55, 19.3MB/s]
 11%|█         | 905M/8.34G [00:35<06:35, 20.2MB/s]
 11%|█         | 908M/8.34G [00:35<06:02, 22.1MB/s]
 11%|█         | 911M/8.34G [00:35<05:41, 23.4MB/s]
 11%|█         | 914M/8.34G [00:35<05:20, 25.0MB/s]
 11%|█         | 917M/8.34G [00:35<05:16, 25.3MB/s]
 11%|█         | 920M/8.34G [00:36<05:28, 24.3MB/s]
 11%|█         | 923M/8.34G [00:36<05:09, 25.8MB/s]
 11%|█         | 926M/8.34G [00:36<05:10, 25.7MB/s]
 11%|█         | 930M/8.34G [00:36<04:47, 27.7MB/s]
 11%|█         | 933M/8.34G [00:36<04:53, 27.2MB/s]
 11%|█         | 936M/8.34G [00:36<05:03, 26.3MB/s]
 11%|█         | 939M/8.34G [00:36<05:09, 25.7MB/s]
 11%|█         | 942M/8.34G [00:36<04:57, 26.8MB/s]
 11%|█         | 946M/8.34G [00:37<04:31, 29.3MB/s]
 11%|█         | 949M/8.34G [00:37<04:30, 29.4MB/s]
 11%|█         | 952M/8.34G [00:37<04:28, 29.6MB/s]
 11%|█         | 955M/8.34G [00:37<04:27, 29.7MB/s]
 11%|█         | 958M/8.34G [00:37<04:36, 28.7MB/s]
 11%|█▏        | 961M/8.34G [00:37<04:35, 28.9MB/s]
 11%|█▏        | 964M/8.34G [00:37<04:36, 28.8MB/s]
 11%|█▏        | 967M/8.34G [00:37<04:31, 29.2MB/s]
 11%|█▏        | 970M/8.34G [00:38<05:26, 24.3MB/s]
 11%|█▏        | 973M/8.34G [00:38<05:12, 25.4MB/s]
 11%|█▏        | 976M/8.34G [00:38<05:16, 25.1MB/s]
 11%|█▏        | 979M/8.34G [00:38<05:23, 24.5MB/s]
 12%|█▏        | 982M/8.34G [00:38<05:32, 23.8MB/s]
 12%|█▏        | 985M/8.34G [00:38<05:22, 24.5MB/s]
 12%|█▏        | 988M/8.34G [00:38<05:10, 25.5MB/s]
 12%|█▏        | 991M/8.34G [00:38<05:11, 25.4MB/s]
 12%|█▏        | 994M/8.34G [00:39<05:16, 25.0MB/s]
 12%|█▏        | 997M/8.34G [00:39<05:01, 26.2MB/s]
 12%|█▏        | 0.98G/8.34G [00:39<04:47, 27.5MB/s]
 12%|█▏        | 0.98G/8.34G [00:39<04:37, 28.5MB/s]
 12%|█▏        | 0.98G/8.34G [00:39<04:45, 27.7MB/s]
 12%|█▏        | 0.99G/8.34G [00:39<04:43, 27.8MB/s]
 12%|█▏        | 0.99G/8.34G [00:39<04:49, 27.3MB/s]
 12%|█▏        | 0.99G/8.34G [00:39<05:12, 25.2MB/s]
 12%|█▏        | 1.00G/8.34G [00:40<06:10, 21.3MB/s]
 12%|█▏        | 1.00G/8.34G [00:40<06:11, 21.2MB/s]
 12%|█▏        | 1.00G/8.34G [00:40<06:39, 19.7MB/s]
 12%|█▏        | 1.00G/8.34G [00:40<08:32, 15.4MB/s]
 12%|█▏        | 1.01G/8.34G [00:40<07:08, 18.4MB/s]
 12%|█▏        | 1.01G/8.34G [00:40<06:16, 20.9MB/s]
 12%|█▏        | 1.01G/8.34G [00:40<05:57, 22.0MB/s]
 12%|█▏        | 1.01G/8.34G [00:41<06:09, 21.3MB/s]
 12%|█▏        | 1.02G/8.34G [00:41<05:51, 22.4MB/s]
 12%|█▏        | 1.02G/8.34G [00:41<05:27, 24.0MB/s]
 12%|█▏        | 1.02G/8.34G [00:41<05:08, 25.5MB/s]
 12%|█▏        | 1.03G/8.34G [00:41<04:55, 26.5MB/s]
 12%|█▏        | 1.03G/8.34G [00:41<04:54, 26.6MB/s]
 12%|█▏        | 1.03G/8.34G [00:41<04:55, 26.5MB/s]
 12%|█▏        | 1.04G/8.34G [00:41<05:02, 25.9MB/s]
 12%|█▏        | 1.04G/8.34G [00:42<04:59, 26.2MB/s]
 12%|█▏        | 1.04G/8.34G [00:42<05:01, 26.0MB/s]
 13%|█▎        | 1.04G/8.34G [00:42<05:07, 25.5MB/s]
 13%|█▎        | 1.05G/8.34G [00:42<04:58, 26.2MB/s]
 13%|█▎        | 1.05G/8.34G [00:42<05:02, 25.9MB/s]
 13%|█▎        | 1.05G/8.34G [00:42<05:05, 25.6MB/s]
 13%|█▎        | 1.06G/8.34G [00:42<04:57, 26.3MB/s]
 13%|█▎        | 1.06G/8.34G [00:42<05:00, 26.0MB/s]
 13%|█▎        | 1.06G/8.34G [00:43<05:06, 25.5MB/s]
 13%|█▎        | 1.06G/8.34G [00:43<04:58, 26.1MB/s]
 13%|█▎        | 1.07G/8.34G [00:43<05:00, 26.0MB/s]
 13%|█▎        | 1.07G/8.34G [00:43<05:00, 25.9MB/s]
 13%|█▎        | 1.07G/8.34G [00:43<05:00, 26.0MB/s]
 13%|█▎        | 1.08G/8.34G [00:43<05:00, 25.9MB/s]
 13%|█▎        | 1.08G/8.34G [00:43<05:03, 25.7MB/s]
 13%|█▎        | 1.08G/8.34G [00:43<05:00, 25.9MB/s]
 13%|█▎        | 1.08G/8.34G [00:44<05:03, 25.7MB/s]
 13%|█▎        | 1.09G/8.34G [00:44<05:13, 24.8MB/s]
 13%|█▎        | 1.09G/8.34G [00:44<05:18, 24.4MB/s]
 13%|█▎        | 1.09G/8.34G [00:44<04:57, 26.2MB/s]
 13%|█▎        | 1.10G/8.34G [00:44<05:01, 25.8MB/s]
 13%|█▎        | 1.10G/8.34G [00:44<04:48, 26.9MB/s]
 13%|█▎        | 1.10G/8.34G [00:44<04:56, 26.2MB/s]
 13%|█▎        | 1.11G/8.34G [00:44<04:54, 26.4MB/s]
 13%|█▎        | 1.11G/8.34G [00:45<05:53, 22.0MB/s]
 13%|█▎        | 1.11G/8.34G [00:45<05:25, 23.8MB/s]
 13%|█▎        | 1.12G/8.34G [00:45<04:48, 26.8MB/s]
 13%|█▎        | 1.12G/8.34G [00:45<04:39, 27.8MB/s]
 13%|█▎        | 1.12G/8.34G [00:45<04:45, 27.1MB/s]
 13%|█▎        | 1.12G/8.34G [00:45<04:48, 26.9MB/s]
 14%|█▎        | 1.13G/8.34G [00:45<04:54, 26.3MB/s]
 14%|█▎        | 1.13G/8.34G [00:45<04:57, 26.0MB/s]
 14%|█▎        | 1.13G/8.34G [00:46<05:12, 24.8MB/s]
 14%|█▎        | 1.14G/8.34G [00:46<05:21, 24.0MB/s]
 14%|█▎        | 1.14G/8.34G [00:46<05:12, 24.8MB/s]
 14%|█▎        | 1.14G/8.34G [00:46<04:55, 26.2MB/s]
 14%|█▎        | 1.14G/8.34G [00:46<05:08, 25.0MB/s]
 14%|█▍        | 1.15G/8.34G [00:46<04:40, 27.5MB/s]
 14%|█▍        | 1.15G/8.34G [00:46<04:49, 26.7MB/s]
 14%|█▍        | 1.15G/8.34G [00:46<04:46, 26.9MB/s]
 14%|█▍        | 1.16G/8.34G [00:47<04:51, 26.5MB/s]
 14%|█▍        | 1.16G/8.34G [00:47<04:50, 26.5MB/s]
 14%|█▍        | 1.16G/8.34G [00:47<04:50, 26.5MB/s]
 14%|█▍        | 1.17G/8.34G [00:47<04:57, 25.9MB/s]
 14%|█▍        | 1.17G/8.34G [00:47<04:56, 26.0MB/s]
 14%|█▍        | 1.17G/8.34G [00:47<04:53, 26.2MB/s]
 14%|█▍        | 1.17G/8.34G [00:47<04:55, 26.0MB/s]
 14%|█▍        | 1.18G/8.34G [00:47<04:56, 25.9MB/s]
 14%|█▍        | 1.18G/8.34G [00:47<05:00, 25.6MB/s]
 14%|█▍        | 1.18G/8.34G [00:48<04:56, 25.9MB/s]
 14%|█▍        | 1.19G/8.34G [00:48<04:57, 25.8MB/s]
 14%|█▍        | 1.19G/8.34G [00:48<04:54, 26.0MB/s]
 14%|█▍        | 1.19G/8.34G [00:48<05:09, 24.8MB/s]
 14%|█▍        | 1.20G/8.34G [00:48<04:51, 26.3MB/s]
 14%|█▍        | 1.20G/8.34G [00:48<04:54, 26.0MB/s]
 14%|█▍        | 1.20G/8.34G [00:48<04:57, 25.7MB/s]
 14%|█▍        | 1.20G/8.34G [00:48<04:57, 25.8MB/s]
 14%|█▍        | 1.21G/8.34G [00:49<04:57, 25.7MB/s]
 15%|█▍        | 1.21G/8.34G [00:49<04:52, 26.1MB/s]
 15%|█▍        | 1.21G/8.34G [00:49<04:53, 26.1MB/s]
 15%|█▍        | 1.22G/8.34G [00:49<04:54, 25.9MB/s]
 15%|█▍        | 1.22G/8.34G [00:49<04:54, 26.0MB/s]
 15%|█▍        | 1.22G/8.34G [00:49<04:54, 26.0MB/s]
 15%|█▍        | 1.22G/8.34G [00:49<04:53, 26.0MB/s]
 15%|█▍        | 1.23G/8.34G [00:49<04:56, 25.7MB/s]
 15%|█▍        | 1.23G/8.34G [00:50<05:52, 21.7MB/s]
 15%|█▍        | 1.23G/8.34G [00:50<06:25, 19.8MB/s]

In [ ]:
# !pip install py7zr

Collecting py7zr
  Downloading py7zr-1.1.0-py3-none-any.whl.metadata (17 kB)
Collecting texttable (from py7zr)
  Downloading texttable-1.7.0-py2.py3-none-any.whl.metadata (9.8 kB)
Collecting pycryptodomex>=3.20.0 (from py7zr)
  Downloading pycryptodomex-3.23.0-cp37-abi3-win_amd64.whl.metadata (3.5 kB)
Collecting brotli>=1.2.0 (from py7zr)
  Using cached brotli-1.2.0-cp312-cp312-win_amd64.whl.metadata (6.3 kB)
Requirement already satisfied: psutil in c:\users\parks\anaconda3\envs\mlstudy_env\lib\site-packages (from py7zr) (7.2.1)
Collecting backports.zstd>=1.0.0 (from py7zr)
  Downloading backports_zstd-1.3.0-cp312-cp312-win_amd64.whl.metadata (7.1 kB)
Collecting pyppmd>=1.3.1 (from py7zr)
  Downloading pyppmd-1.3.1-cp312-cp312-win_amd64.whl.metadata (5.6 kB)
Collecting pybcj>=1.0.6 (from py7zr)
  Downloading pybcj-1.0.7-cp312-cp312-win_amd64.whl.metadata (4.0 kB)
Collecting multivolumefile>=0.2.3 (from py7zr)
  Downloading multivolumefile-0.2.3-py3-none-any.whl.metadata (6.3 kB)
Collecting inflate64>=1.0.4 (from py7zr)
  Downloading inflate64-1.0.4-cp312-cp312-win_amd64.whl.metadata (4.5 kB)
Downloading py7zr-1.1.0-py3-none-any.whl (71 kB)
Downloading backports_zstd-1.3.0-cp312-cp312-win_amd64.whl (313 kB)
Using cached brotli-1.2.0-cp312-cp312-win_amd64.whl (369 kB)
Downloading inflate64-1.0.4-cp312-cp312-win_amd64.whl (35 kB)
Downloading multivolumefile-0.2.3-py3-none-any.whl (17 kB)
Downloading pybcj-1.0.7-cp312-cp312-win_amd64.whl (24 kB)
Downloading pycryptodomex-3.23.0-cp37-abi3-win_amd64.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 1.8/1.8 MB 16.4 MB/s  0:00:00
Downloading pyppmd-1.3.1-cp312-cp312-win_amd64.whl (46 kB)
Downloading texttable-1.7.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: texttable, brotli, pyppmd, pycryptodomex, pybcj, multivolumefile, inflate64, backports.zstd, py7zr

   -------- ------------------------------- 2/9 [pyppmd]
   -------- ------------------------------- 2/9 [pyppmd]
   -------- ------------------------------- 2/9 [pyppmd]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ------------- -------------------------- 3/9 [pycryptodomex]
   ----------------- ---------------------- 4/9 [pybcj]
   ------------------------------- -------- 7/9 [backports.zstd]
   ----------------------------------- ---- 8/9 [py7zr]
   ---------------------------------------- 9/9 [py7zr]

Successfully installed backports.zstd-1.3.0 brotli-1.2.0 inflate64-1.0.4 multivolumefile-0.2.3 py7zr-1.1.0 pybcj-1.0.7 pycryptodomex-3.23.0 pyppmd-1.3.1 texttable-1.7.0

In [ ]:
import py7zr
import os

target_dir = 'kkbox_data'
files = [f for f in os.listdir(target_dir) if f.endswith('.7z')]

for file in files:
    file_path = os.path.join(target_dir, file)
    with py7zr.SevenZipFile(file_path, mode='r') as z:
        z.extractall(path=target_dir)
    print(f"{file} 해제 완료!")

압축 해제 시작...
members_v3.csv.7z 해제 완료!
sample_submission_v2.csv.7z 해제 완료!
sample_submission_zero.csv.7z 해제 완료!
train.csv.7z 해제 완료!
train_v2.csv.7z 해제 완료!
transactions.csv.7z 해제 완료!
transactions_v2.csv.7z 해제 완료!
user_logs.csv.7z 해제 완료!
user_logs_v2.csv.7z 해제 완료!

최종 파일 목록: ['data', 'members_v3.csv', 'members_v3.csv.7z', 'sample_submission_v2.csv.7z', 'sample_submission_zero.csv', 'sample_submission_zero.csv.7z', 'train.csv', 'train.csv.7z', 'train_v2.csv.7z', 'transactions.csv', 'transactions.csv.7z', 'transactions_v2.csv.7z', 'user_logs.csv', 'user_logs.csv.7z', 'user_logs_v2.csv.7z', 'WSDMChurnLabeller.scala']

In [1]:
import pandas as pd


# 1. 학습 및 테스트 관련 데이터
df_train_v2 = pd.read_csv('./csv_data/train_v2.csv')
df_sample_sub = pd.read_csv('./csv_data/sample_submission_v2.csv')

# 2. 유저 정보 데이터
df_members = pd.read_csv('./csv_data/members_v3.csv')

# 3. 결제 내역 데이터 
df_trans_v2 = pd.read_csv('./csv_data/transactions_v2.csv')

# 4. 사용자 활동 로그 데이터
df_logs_v2 = pd.read_csv('./csv_data/user_logs_v2.csv')

In [2]:
df_members

,msno,city,bd,gender,registered_via,registration_init_time
0,Rb9UwLQTrxzBVwCB6+bCcSQWZ9JiNLC9dXtM1oEsZA8=,1,0,NaN,11,20110911
1,+tJonkh+O1CA796Fm5X60UMOtB6POHAwPjbTRVl/EuU=,1,0,NaN,7,20110914
2,cV358ssn7a0f7jZOwGNWS07wCKVqxyiImJUX6xcIwKw=,1,0,NaN,11,20110915
3,9bzDeJP6sQodK73K5CBlJ6fgIQzPeLnRl0p5B77XP+g=,1,0,NaN,11,20110915
4,WFLY3s7z4EZsieHCt63XrsdtfTEmJ+2PnnKLH5GY4Tk=,6,32,female,9,20110915
...,...,...,...,...,...,...
6769468,VSGkb3hyBRUtb/b1MQUZbvOkktS3vKLnhMHW0CF8eyU=,1,0,NaN,7,20151020
6769469,nWjH7glPkZ7jOVaCRwwjlpmp0T1hSWdv8hMJxiWCwKc=,1,0,NaN,7,20151020
6769470,GH+b5+1tlv7ZZXsA8upBzVXMTLyffKcsF7WoU8b5rOI=,15,26,female,4,20151020
6769471,XVlwT3fdCFGKqerEKBzUIjK+jzI6jzSke4cDMVhYyjE=,1,0,NaN,4,20151020
6769472,isBt+JlgvZRNy6lxVr5vvuJ4lD00ofTaKyJ+uRnGcPg=,1,0,NaN,4,20151021

In [18]:
df_logs_v2.head(50)

,msno,date,num_25,num_50,num_75,num_985,num_100,num_unq,total_secs
0,u9E91QDTvHLq6NXjEaWv8u4QIqhrHk72kE+w31Gnhdg=,20170331,8,4,0,1,21,18,6309.273
1,nTeWW/eOZA/UHKdD5L7DEqKKFTjaAj3ALLPoAWsU8n0=,20170330,2,2,1,0,9,11,2390.699
2,2UqkWXwZbIjs03dHLU9KHJNNEvEkZVzm69f3jCS+uLI=,20170331,52,3,5,3,84,110,23203.337
3,ycwLc+m2O0a85jSLALtr941AaZt9ai8Qwlg9n0Nql5U=,20170331,176,4,2,2,19,191,7100.454
4,EGcbTofOSOkMmQyN1NMLxHEXJ1yV3t/JdhGwQ9wXjnI=,20170331,2,1,0,1,112,93,28401.558
5,qR/ndQ5B+1cY+c9ihwLoiz+RFiqEnGyQKo32ZErEVKo=,20170331,3,0,0,0,39,41,9786.842
6,N6ch5ArfJixq9mvARJv9ip1D11uvDVazz6Qup5mX7DI=,20170330,9,1,0,0,18,26,4920.255
7,JEjl2W1ivEI6epeobW3n5rDg/r6PJm4OJhtmhwYaQIc=,20170331,181,68,5,3,54,291,22433.105
8,lPK4IYIFdfTT6pq7x2dSV1Vy9j9hNMWzf7XfYBUBz5E=,20170331,3,0,1,1,181,150,46240.281
9,cDgnvwQwCwru2m3zcSuK5oTr6pr1nMPQ/6RerOmxrs0=,20170331,5,4,1,1,30,31,7881.618
10,Cwk7eMLB8Gn8WuzECC2i/GboGXOfkGhS8ju6Brrk2F8=,20170331,7,1,2,7,69,74,18169.176
11,6eT/NGMljpNgEeqTYIdhkc/dvUik+b+41sBNrXJ0cBQ=,20170324,78,5,3,2,8,85,3490.020
12,PVoh0C3fQb1qPNLj7SZ0fKzFC8kStQ/uT2bV358G/1E=,20170325,7,1,0,0,45,21,8159.811
13,cK5XYJqbmsRYasnA48AkJzUna8Ijge8wAp/r3Is/N10=,20170324,1,0,0,0,17,18,4012.814
14,zv12NEuyP2XxcgTDu89mGnPLdnfq8xhBY4jQl8JYLxk=,20170325,5,3,2,1,34,43,9060.814
15,NCRcE4eNurBdOoRk0m+hwDz94xBN6+KL5PTwen4hmWU=,20170325,40,6,2,2,131,149,29400.889
16,q5iH4iDmaFeyz2ZhvQsWlwzhfMhL98chdm4usnV4Ugk=,20170324,4,2,0,1,79,80,20312.570
17,dgjSYdCsI6j51myzxWAdm9jebVRsdgbsvwGcigEUv+U=,20170325,3,1,0,2,155,156,36424.954
18,Q6XdUeVvsXNF/7o0IjPbcSg6dCsFlsRsdGLuiT5UIiI=,20170318,1,1,1,0,136,123,37989.716
19,TWrqEpm0U75ZWW6CHzdp3hVDE7WCQLBX4czgXMvyldY=,20170317,18,1,2,3,170,162,42203.675
20,IXGl03MIJlMcJi2OQX2uIsL6MOpQGmmbs0gv8hHya0g=,20170317,4,0,0,0,41,26,9350.104
21,6TUBGALub4mtanT3rrvgztKmyViZcUpJ5bn/1R5jaPE=,20170318,21,7,0,0,19,45,6011.614
22,MP3mnG9WcBVvToAfUT/ArhdyZ4SqEfnG3Ab/XsZF1jw=,20170318,13,2,3,3,47,67,13721.915
23,HlAmwB3IHrDG4ViLtgggCLZOodjpFxLRTFIide0Q0RI=,20170318,44,1,0,2,52,90,13119.719
24,1x5QHqWV6tTSqoVAQ1rX0lveYhkgLISDczHtibAIQxs=,20170318,3,0,0,2,16,21,4206.532
25,xZmokPACIvbzXoCrwp+nxnB3SLiLLT+QnFy6ZOYofLE=,20170318,0,1,0,0,22,3,4194.039
26,8CqUdcMrqjWnGSlDcJPySyOjQn3UALKPq+nqBNwhrAw=,20170318,2,1,0,0,84,59,19074.350
27,azWX70ixfwJqo5yIbjFmG8TG8wMpAwdL0SFu9B9uzMo=,20170318,3,2,1,1,39,35,9707.448
28,0h/f+mzEXO0nt5dZRZJQHfe8Du8tY8eQnmoN2GGuNYI=,20170318,6,0,0,2,22,28,5961.087
29,9Ok7Pg4TEjBi11/UCYzTvjpKUbSIqnEeMqHd2LjUlFs=,20170318,9,0,0,0,26,35,6617.381
30,EtGyxIx5kfemuxyz/EF/X+fmPi4PsvU3gK/otorxE6M=,20170318,14,2,2,4,158,91,36704.541
31,vg16qtAlmVzBB8Ro/Nw4ufokUufkmiPWD+lfYXv5gwA=,20170317,4,3,2,3,43,48,11457.380
32,9mjgbJOxafEHYvsXkTDbMmYdlkiwPhIZZDhkzUJH08c=,20170318,0,0,1,0,17,17,4656.920
33,E+CHqAfaErdGBAL4FB7evsPA3n303WLzgU3jKaWPJWQ=,20170318,67,12,3,1,13,83,5862.302
34,vZedzsNYrZsRBhag8uivTbeJR3lL74kzULRi3XM4fes=,20170318,25,8,3,1,52,60,14053.858
35,Dde9YoZqShj9wZAgEm0mc+V995QOExh+1WRlL9oMQJg=,20170318,34,13,7,6,83,74,24825.041
36,pmWPGqnnkA0xpwq/f+FFplRqbh4fejmnufOYLRHNmCs=,20170318,10,2,1,3,76,63,19977.625
37,6cWurckm4K0l8cBEO5t3EqkY0dsdcxreQepdFneFX8I=,20170319,12,2,7,3,51,23,14183.384
38,9T9rI8iaoEpoZRWQ0BIiql+h0yzZ9aBaaSoLT7v1xI8=,20170318,5,1,0,1,109,26,28023.897
39,48b751JtBt3llSn5aSbVQgBHqInG72P6NnjLiSkT/cg=,20170319,0,1,3,0,11,12,2993.476
40,b74Xot5HcOL8YQGiuwLw+Cm7RyGV2fOkGczJomGLocg=,20170318,25,8,6,3,210,165,54995.604
41,PaVUCAJf0q9Nk+UJP/cIwe5p8GkaiPIHO6rwMJAEGBE=,20170319,5,6,0,5,135,143,34806.683
42,IYbqsaIlPpGu/an6G3YnpgAnwlJYp/90wBRGakRveUg=,20170319,0,0,0,0,203,32,38807.000
43,gdioAwGvWSwyt6rsITIZ/fms7Z3r/Sfu1jdvakaCy1g=,20170319,71,22,11,9,63,162,21403.807
44,l9PVEmVI0awlEy5TS31liAQnrEKASa9TtmntXb4Cg1s=,20170319,6,1,1,5,31,31,9379.515
45,gOez8s5b1FYEwuXnrcLwIcDUo7oDpHADvhCnyswId/4=,20170319,80,16,4,7,64,157,17744.003
46,u+dWCJZniExrQ9lzjymAL2ogydG+9/db/36GZZs3ifg=,20170319,7,2,1,0,19,29,5048.380
47,JPJGYcF7q88Bot5kG8a9wm3O1XUfk8DK7mFLrET2xas=,20170319,15,1,0,0,20,32,5010.391
48,c4QNJRdk48RdmAuvYNqgf0uJqJMQ8f7Ri/mFjQo2d+U=,20170319,17,6,2,5,34,22,10849.311
49,ztW6+r14N1nY1vxMblNsOvkPSu2Dlhn/JvUQEFIk/Gg=,20170319,11,3,4,3,156,106,39534.973

In [ ]:
df = pd.merge(df_logs_v2,df_members,on='msno',how='inner')

In [17]:
df

,msno,date,num_25,num_50,num_75,num_985,num_100,num_unq,total_secs,city,bd,gender,registered_via,registration_init_time
0,u9E91QDTvHLq6NXjEaWv8u4QIqhrHk72kE+w31Gnhdg=,20170331,8,4,0,1,21,18,6309.273,1,0,NaN,7,20161220
1,nTeWW/eOZA/UHKdD5L7DEqKKFTjaAj3ALLPoAWsU8n0=,20170330,2,2,1,0,9,11,2390.699,1,0,NaN,7,20160726
2,2UqkWXwZbIjs03dHLU9KHJNNEvEkZVzm69f3jCS+uLI=,20170331,52,3,5,3,84,110,23203.337,6,20,female,4,20160714
3,ycwLc+m2O0a85jSLALtr941AaZt9ai8Qwlg9n0Nql5U=,20170331,176,4,2,2,19,191,7100.454,4,0,NaN,9,20170326
4,EGcbTofOSOkMmQyN1NMLxHEXJ1yV3t/JdhGwQ9wXjnI=,20170331,2,1,0,1,112,93,28401.558,1,0,NaN,7,20160723
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18395945,FGpiy2mB+vXLKziYRcY/xJcJEFJfRDfUqlU+p760f7E=,20170314,0,0,0,0,1,1,248.058,1,0,NaN,7,20170126
18395946,iZRjKNMrw5ffEbfXODLhV/0tJLPbOH3am1WYDgqBf8Q=,20170306,0,0,0,0,1,1,311.000,13,0,NaN,4,20160724
18395947,yztw4Y0EggG0w2wPkbMZx7ke7saSx7dLSfMheHZG/DQ=,20170331,0,0,0,0,17,1,3973.189,13,28,male,9,20110216
18395948,swCHwkNx30/aENjq30qqaLlm7bUUytbMXdz1bH7g0Jk=,20170307,0,0,0,1,0,1,179.278,6,24,female,9,20080203
18395949,pDQSIFZchNPmOproRzaNzy51/8yRXzLK3vvDXKzzGLQ=,20170329,0,0,0,0,1,1,264.288,4,35,male,3,20150212

In [19]:
df_trans_v2

,msno,payment_method_id,payment_plan_days,plan_list_price,actual_amount_paid,is_auto_renew,transaction_date,membership_expire_date,is_cancel
0,++6eU4LsQ3UQ20ILS7d99XK8WbiVgbyYL4FUgzZR134=,32,90,298,298,0,20170131,20170504,0
1,++lvGPJOinuin/8esghpnqdljm6NXS8m8Zwchc7gOeA=,41,30,149,149,1,20150809,20190412,0
2,+/GXNtXWQVfKrEDqYAzcSw2xSPYMKWNj22m+5XkVQZc=,36,30,180,180,1,20170303,20170422,0
3,+/w1UrZwyka4C9oNH3+Q8fUf3fD8R3EwWrx57ODIsqk=,36,30,180,180,1,20170329,20170331,1
4,+00PGzKTYqtnb65mPKPyeHXcZEwqiEzktpQksaaSC3c=,41,30,99,99,1,20170323,20170423,0
...,...,...,...,...,...,...,...,...,...
1431004,zwF50wwaJI2TBKWhB42HRBJ6EQK0jgSo1Xmwb9Jq3SU=,32,180,536,536,0,20170215,20170817,0
1431005,zx/h5MzQQmsSat04wSfGpHp6N8aWLLwM1+7OV7ujmPY=,41,30,149,149,1,20170306,20170406,0
1431006,zxvgjIKjy18Fm+cIWUfYKr68z09+ILBxuMW0DnbeUZ8=,41,30,99,99,1,20170308,20170408,0
1431007,zzNhkExbpzmpjp9tXefiCUBtgNLgS+vZE7fFfTRDJVc=,38,30,149,149,0,20170318,20170417,0
1431008,zzZmdSzz7J9oyC/5nHr/HBvWg6k+p2W15b6lt/VKUQE=,32,180,699,699,0,20161212,20170613,0

In [ ]:
import pandas as pd

# 1. 파일 불러오기 (경로 설정: ./data/...)
# 파일명은 다운로드하신 이름에 맞춰 수정하세요 (예: demographics.csv, raw_data.csv)
df_demo = pd.read_csv('./gb/sports_gb_F.csv')
df_raw = pd.read_csv('./gb/sports_gb_A.csv')
df_info = pd.read_csv('./gb/sports_gb_total.csv')

# 2. 데이터 병합 (UserID를 기준으로 기질과 행동을 합침)
# 인구통계(기질) 데이터와 베팅 로그(행동) 데이터를 결합합니다.

In [4]:
df_demo

          UserID     DateBet  StakeF    WinF  BetsF
0        1324354  2005-10-01   40.00    0.00      6
1        1324354  2005-10-12   50.00    0.00      2
2        1324354  2005-09-24  132.48  132.48      7
3        1324354  2006-06-18   12.55    0.00      2
4        1324354  2005-10-13   15.00    0.00      3
...          ...         ...     ...     ...    ...
2108611  1405190  2006-03-30    6.80    6.75      4
2108612  1405190  2006-04-01    0.00    5.20      0
2108613  1405190  2006-04-08    3.15    0.00      3
2108614  1405190  2006-04-20    0.00    4.16      0
2108615  1405190  2006-04-29    6.21    0.00      7

[2108616 rows x 5 columns]

In [15]:
df_raw

         UserID     DateBet  StakeL   WinL  BetsL
0       1324354  2005-09-21    5.00   0.00      1
1       1324354  2006-06-17   29.69  22.55      4
2       1324354  2006-06-18   10.00   0.00      1
3       1324354  2005-09-26   60.00   0.00      2
4       1324354  2005-05-08   80.00   0.00      2
...         ...         ...     ...    ...    ...
710592  1405185  2005-12-04   20.00   0.00      2
710593  1405185  2005-12-10    6.00   0.00      1
710594  1405189  2005-03-13    6.00   9.10      2
710595  1405189  2005-05-02    3.00   8.70      1
710596  1405189  2006-06-26    1.00   0.00      1

[710597 rows x 5 columns]

In [14]:
df_info

,UserID,CountryID,Gender,BirthYear,DateReg,TimeReg,Date1Dep,Date1Bet,Date1Spo,StakeF,...,StakeA,WinF,WinL,WinA,BetsF,BetsL,BetsA,DaysF,DaysL,DaysA
0,1324354,276,1,1963.0,2005-02-01,00:01,2005-02-24,2005-02-24,2005-02-24,15750.3800,...,17896.8500,15010.9000,1809.9500,16820.8500,727,71,798,231,33,233
1,1324355,300,1,1983.0,2005-02-01,00:05,2005-02-01,2005-02-01,2005-02-01,639.2998,...,663.9998,569.3700,11.2000,580.5700,286,21,307,99,7,101
2,1324356,276,1,1977.0,2005-02-01,00:05,2005-02-01,2005-02-02,2005-02-02,898.8100,...,1600.6300,336.3600,649.2700,985.6300,116,126,242,48,27,54
3,1324358,752,1,1981.0,2005-02-01,00:08,2005-02-01,2005-02-01,2005-02-01,247.6970,...,336.2897,153.8755,55.9819,209.8574,7,4,11,5,1,5
4,1324360,792,1,1978.0,2005-02-01,00:09,2005-02-02,2005-02-02,2005-02-02,685.9424,...,692.6065,623.8984,3.0528,626.9512,386,8,394,58,4,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46334,1405183,276,1,1966.0,2005-02-28,23:44,2005-03-03,2005-03-04,2005-03-04,88.7600,...,190.8900,21.4600,84.4300,105.8900,45,39,84,23,13,24
46335,1405184,276,1,1978.0,2005-02-28,23:46,2005-02-28,2005-03-01,2005-03-01,315.8800,...,612.6300,226.8600,320.7700,547.6300,123,100,223,34,23,36
46336,1405185,276,1,1976.0,2005-02-28,23:50,2005-11-08,2005-11-08,2005-11-08,13.0000,...,137.7100,16.0000,86.7100,102.7100,2,18,20,2,5,5
46337,1405189,276,1,1983.0,2005-02-28,23:54,2005-03-01,2005-03-01,2005-03-01,414.0900,...,424.0900,421.2900,17.8000,439.0900,185,4,189,53,3,54
46338,1405190,276,1,1980.0,2005-02-28,23:57,2005-03-03,2005-03-03,2005-03-03,84.1100,...,84.1100,16.1100,0.0000,16.1100,32,0,32,8,0,8

In [8]:
# fixed 합계
fixed_agg = df_demo.groupby("UserID").agg({
    "StakeF": "sum",
    "WinF": "sum",
    "BetsF": "sum"
}).reset_index()

# live 합계
live_agg = df_raw.groupby("UserID").agg({
    "StakeL": "sum",
    "WinL": "sum",
    "BetsL": "sum"
}).reset_index()

# merge
agg_rebuilt = fixed_agg.merge(live_agg, on="UserID", how="outer").fillna(0)
agg_rebuilt["StakeA"] = agg_rebuilt["StakeF"] + agg_rebuilt["StakeL"]

In [9]:
compare = df_info.merge(agg_rebuilt, on="UserID", suffixes=("_file3", "_rebuilt"))

(compare["StakeF_file3"] - compare["StakeF_rebuilt"]).abs().max()

np.float64(6548.66)